- pkg/parsers/starknet/hint.go
- pkg/parsers/starknet/program.go
- Avoid prepending "failed to..." or "error" to error messages.
- Fix typos.
> Use idiomatic error messages

- pkg/hintrunner/error.go
- pkg/hintrunner/hint.go
- pkg/hintrunner/hint_test.go
- pkg/hintrunner/hintrunner.go
- pkg/hintrunner/hintrunner_test.go
- pkg/hintrunner/operand.go
- pkg/hintrunner/operand_test.go
- pkg/hintrunner/testutils.go
- pkg/safemath/error.go
- pkg/safemath/safemath.go
- pkg/vm/memory/memory_value.go
- pkg/vm/vm.go
- pkg/vm/vm_test.go
Added a `Hintrunner` as an external component for the VM. The `Hintrunner` is the part of the project that will run the hints by  which would allow for any of the users of the VM to define their own hints if they want.
This will also favor atomic and parallel works on hints, since all the tools for interacting with the VM for hints has been implemented.
`Alloc` and `TestLessThan` hints are implemented as well as use example.
Fixes #31
> Feature: Add a hintrunner for the Vm

- pkg/vm/instruction.go
- pkg/vm/instruction_test.go
Adds additional test cases for instruction decoding covering incorrectly set bits for instruction's flags. Resolves #17.
> test: instruction decoding

- pkg/hintrunner/operand.go
Puts methods after the struct types
> Organize hintrunner/operand.go

- pkg/vm/memory/memory.go
- pkg/vm/memory/memory_value.go
Reading through the codebase, refactoring the error messages as I go, hopefully improving consistency. Feel free to close the PR if the changes aren't what you're looking for.
> Simplify error handling in `memory` package

- pkg/vm/memory/memory_manager.go
- pkg/vm/memory/memory_value.go
This is essentially a poor mans union.
``` c
struct {
union {
felt f.Element
memoryAddress MemoryAddress
}
bool isFelt
bool isMemoryAddress
}
```
This results in a smaller `MemoryValue`.
Helps us in 2 ways,
Makes segments take less space in memory (less total memory consumption)
and makes copying MemoryValue instances cheaper since there are less bytes to copy (speed up)
Before;
```
BenchmarkVMRun-16    	Loading program at /home/omer/Documents/cairo-vm-go/fib_compiled.json
Running....
93	  12089788 ns/op	11495034 B/op	      44 allocs/op
PASS
```
After
```
BenchmarkVMRun-16    	Loading program at /home/omer/Documents/cairo-vm-go/fib_compiled.json
Running....
100	  11596486 ns/op	 8215796 B/op	      44 allocs/op
PASS
```
a marginal speed up and a significant reduction in total memory …
> make felt and address in MemoryValue share the same bytes

- pkg/hintrunner/hint.go
- pkg/hintrunner/operand.go
- pkg/vm/builtins/range_check.go
- pkg/vm/memory/memory_value.go
- pkg/vm/vm.go
* Updated functions descriptions to be updated with current code
* Updated functions and var names as well
* Deleted some old comments and code
> Chore: some housekeeping on memory pkg

- pkg/runners/zero/zero.go
- pkg/vm/builtins/range_check.go
- pkg/vm/builtins/range_check_test.go
- pkg/vm/memory/memory.go
- pkg/vm/memory/memory_test.go
- pkg/vm/memory/memory_value.go
- pkg/vm/vm.go
* Make the VM fail when reading an unknown memory value
* Make Builtin inference fail when it is not supposed to infer anything
* UnknownValue is now UnknownAddress for Empty Addresses and UnknownValue are now Empty Values
* Update tests accordingly
Resolves #100
> Feat: Adds failure on reading from unknown values

- pkg/assembler/assembler.go
- pkg/assembler/grammar_test.go
Increase parser look ahead so it could select the right production to expand. It couldn't correctly decide between these two instructions:
* jmp rel expr
* jmp rel <dst> if <exrp> != 0
Fixes #104
> Fix(assembler): increase parser lookahead

- Makefile
`make testall` fails integration tests with:
```
--- FAIL: TestCairoZeroFiles (7.46s)
cairozero_test.go:36: testing: cairo_files/factorial.cairo
cairozero_test.go:52: cairo-vm run cairo_files/factorial_compiled.json: fork/exec ../bin/cairo-vm: no such file or directory
cairozero_test.go:36: testing: cairo_files/fib.cairo
cairozero_test.go:52: cairo-vm run cairo_files/fib_compiled.json: fork/exec ../bin/cairo-vm: no such file or directory
cairozero_test.go:36: testing: cairo_files/simple.cairo
cairozero_test.go:52: cairo-vm run cairo_files/simple_compiled.json: fork/exec ../bin/cairo-vm: no such file or directory
--- FAIL: TestFailingRangeCheck (1.05s)
cairozero_test.go:247:
Error Trace:	/home/jmjac/go/src/github.com/NethermindEth/cairo-vm-go/integration_tests/cairozero_test.go:247
Error: …
```
> Fix testall

- pkg/vm/vm_test.go
A test for an  instruction that checks if two values are equal. It is represented by the following syntax:
`<left_hand_op> = <right_hand_op>`
It ensures that both sides are equal and rejects the program execution otherwise.
For example: 
` [reg0 + offop0] ◦ imm`
where  `◦`  is an arithmetic operator (addition or multiplication), and `imm` is any fixed field element. 
Division and subtraction are represented as multiplication and addition (respectively) with a different order of operands.
Issue #118
> More tests for assert equal Instruction

- pkg/hintrunner/hint.go
- pkg/hintrunner/hint_test.go
- pkg/vm/memory/memory_value.go
Resolves #124.  As I understand this hint handles printing values between `start` and `end` addresses. I don't like getting underlying type of `ResOperand` but this seems to be necessary to figure out how many values do we need to print. Also this won't work with `Immediate` because it's a value not an address
> Feat: debugPrint hint

- pkg/hintrunner/hint.go
- pkg/hintrunner/hint_bechmark_test.go
- pkg/hintrunner/hint_test.go
Implements the uint512 div mod uint256 hint for the hint runner. Resolves #112.
> feat: uint512 div mod

- pkg/assembler/instruction.go
- pkg/assembler/instruction_test.go
The cairo1 compiler generates jnz with ap++ for some range-check related code. To support this code in our assembler, the ap_change check should be removed.
See the referenced issue for more context.
Fixes #184
> pkg/assembler: allow JNZ with ap_change

- pkg/assembler/assembler.go
- pkg/assembler/assembler_test.go
- pkg/assembler/grammar.go
Fixes #186
The idea is taken from here:
https://github.com/alecthomas/participle/issues/112#issuecomment-703019668
> assembler: parse negative values in Offset properly

- integration_tests/cairo_files/alloc.cairo
The test uses the `alloc()` function that in turn uses the legacy AllocSegment hint.
The #172 makes it possible to use alloc now,
so we can add an integration test for that.
> add AllocSegment Cairo0 hint detection test

- pkg/hintrunner/zero/zerohint.go
- pkg/parsers/zero/zero.go
- pkg/parsers/zero/zero_test.go
- pkg/runners/zero/program.go
This allows us to do less redundant type assertions while handling the zero prog identifiers.
We may go even further, but this step is enough for now to make zero hints handler less awkward.
The `.([]zero.Reference)` assertion was not working as the slice contained `[]any` instead.
Instead of rewriting the code to handle even more
weakly typed `any` values, this patch improves the Identifier objects typing.
This makes type assertions and slice conversions unnecessary.
> pkg/parsers/zero: improve Identifiers typing

- pkg/hintrunner/zero/hintparser.go
- pkg/hintrunner/zero/hintparser_test.go
References may include the multiplication inside them.
Let's take this like of code for the example:
https://github.com/starkware-libs/cairo-lang/blob/caba294d82eeeccc3d86a158adb8ba209bf2d8fc/src/starkware/cairo/common/math.cairo#L193
It will produce a reference like this:
```json
{
"cairo_type": "felt",
"full_name": "starkware.cairo.common.math.assert_le_felt.arc_prod",
"references": [
{
"ap_tracking_data": {
"group": 1,
"offset": 8
},
"pc": 14,
"value": "cast([ap + (-5)] * [ap + (-1)], felt)"
}
],
"type": "reference"
}
```
> pkg/hintrunner/zero: allow multiplication binary ops in references

- integration_tests/cairozero_test.go
- pkg/hintrunner/core/hint.go
- pkg/hintrunner/core/hint_benchmark_test.go
- pkg/hintrunner/core/hint_test.go
- pkg/hintrunner/zero/hint_reference_resolver.go
- pkg/hintrunner/zero/hintcode.go
- pkg/hintrunner/zero/zerohint.go
In turn, `assert_le_felt` is needed for some other functions that use cairo0 hints, like `is_nn`.
> implement cairo0 hints needed for assert_le_felt

- pkg/hintrunner/zero/hintcode.go
- pkg/hintrunner/zero/zerohint.go
- pkg/utils/math.go
This hint uses the assert_le_felt beneath it, but
it was implemented beforehand.
This PR has no tests included since #204 is not solved yet. I used a couple of Cairo0 scripts to test this functionality with a set of different arguments to cover both hints that are a part of `is_nn` function.
(One of them handles negatives while another is for the non-negatives.)
Refs #164
> implement is_nn Cairo0 hint

- pkg/hintrunner/zero/zerohint.go
- pkg/hintrunner/zero/zerohint_math.go
Since we use this combination that often, it's worth moving it to a new function so we can handle the error exactly once per every operander (instead of twice).
> pkg/hintrunner/zero: refactor Resolve+FieldElement idiom

- pkg/hintrunner/zero/hintcode.go
- pkg/hintrunner/zero/zerohint.go
- pkg/hintrunner/zero/zerohint_math.go
- pkg/hintrunner/zero/zerohint_math_test.go
- pkg/hintrunner/zero/zerohint_test.go
- pkg/hintrunner/zero/zerohint_utils_test.go
- pkg/utils/constant.go
- pkg/utils/math.go
- pkg/utils/math_test.go
This hint required a builtins support from the test runner.
I tested this hint with our VM as well.
The results for tests are gathered from the cairo-run executions for the same values.
> pkg/hintrunner/zero: implement assert250bits Cairo0 hint

- cmd/cli/main.go
- pkg/runners/zero/zero.go
The Blockifier-style API uses the PC-based contract class entry point.
See #237 for more context
> pkg/runners/zero: add a way to use PC offset as an entrypoint

- pkg/hintrunner/zero/hintcode.go
- pkg/hintrunner/zero/zerohint.go
- pkg/hintrunner/zero/zerohint_math.go
- pkg/hintrunner/zero/zerohint_math_test.go
This commit introduces a cairo0 hint named "Sqrt" to calculate the square root of a given value while ensuring it falls within a specified range ([0, 2**250)). 
The calculation utilizes the [Sqrt()](https://github.com/holiman/uint256/blob/v1.2.3/uint256.go#L1307) function from the `"github.com/holiman/uint256"` library, setting z (root) to ⌊√x⌋ (value), the largest integer such that z² ≤ x, and returns z. 
To ensure the value remains within the specified range, the `FeltLt()` function from `"github.com/NethermindEth/cairo-vm-go/pkg/utils"` is utilized.
Accompanying tests cover various scenarios:
- Testing the square root of 25, which is expected to be 5.
- Handling zero input value, which is expected to be 0
- Verifying the square root of 50, expected to be 7.xxx.... (rounded to 7).
- …
> Add: Cairo0 Sqrt hint

- pkg/hintrunner/utils/math_utils.go
- pkg/hintrunner/zero/hintcode.go
- pkg/hintrunner/zero/zerohint.go
- pkg/hintrunner/zero/zerohint_ec.go
- pkg/hintrunner/zero/zerohint_ec_test.go
This hint calculates the slope between two points on an elliptic curve. A helper function `LineSlope()` is used for calculating the slope.
Test cases for this hint have been compared with the results produced by the  VM implementations in Rust and Go.
LineSlope method link: https://github.com/lambdaclass/cairo-vm_in_go/blob/31c3628bc10ebc1628685b3cdfa72d0e938b533e/pkg/builtins/ec_op.go#L258
> Implement cairo0 compute slope V1 hint

- pkg/hintrunner/zero/zerohint_dictionaries_test.go
- pkg/hintrunner/zero/zerohint_ec_test.go
- pkg/hintrunner/zero/zerohint_math_test.go
- pkg/hintrunner/zero/zerohint_memcpy_test.go
- pkg/hintrunner/zero/zerohint_signature_test.go
- pkg/hintrunner/zero/zerohint_usort_test.go
@cicr99 As discussed today, here is the PR following the merge of :
https://github.com/NethermindEth/cairo-vm-go/pull/382#issuecomment-2093492811
This PR makes sure there is no extra scope in any test
> Improve Scope Usage Consistence in all Tests

- pkg/hintrunner/zero/zerohint_dictionaries.go
- pkg/hintrunner/zero/zerohint_ec.go
- pkg/hintrunner/zero/zerohint_others.go
- pkg/hintrunner/zero/zerohint_usort.go
- pkg/hintrunner/zero/zerohint_usort_test.go
@cicr99  I also renamed all `new...` function that ended with `Hinter` instead of `Hint`
Corrected the wrong name `SquashDictInnerAssertKeys` instead of `SquashDictInnerAssertLenKeys` 
Note : UsortVerifyMultiplicityBody is wrongly implemented
> [feat]: Annotate usort and dict hints + few improvements 

- pkg/hintrunner/zero/zerohint_usort.go
- pkg/hintrunner/zero/zerohint_usort_test.go
- pkg/hintrunner/zero/zerohint_utils_test.go
Resolves #391 
This PR rectifies `UsortVerifyMultiplicityBody` hint previously wrongly implemented.
I also added more tests, always with a descending list as input (required). 
note that `current_pos` does not need to be assigned in scope , i also rectified this. `current_scope` is calculated for each iteration with `positions.pop()` and is not required in scope.
Also, i added a reassignement of `positions` in the scope because it was missing, `positions` needs to be updated in scope otherwise the array will ne be emptied in the recursive call, this will cause an infinite loop when calling usort
> [bug]: implement correctly `UsortVerifyMultiplicityBody` hint

- pkg/vm/vm.go
Previously the max memory index in a memory file was calculated assuming that the last address in the file would represent the highest index.
```
// calculate the max memory index
lastContentInd := len(content) - (addrSize + feltSize)
lastMemIndex := binary.LittleEndian.Uint64(content[lastContentInd : lastContentInd+addrSize])
```
But this is not always the case. The memory file generated by the python vm can have the addresses in the file written out of order. That means the last address in the file need not be the largest address.
This PR changes that logic. Now the code will iterate over all the addresses in the memory file and find the largest one before initialising the decoded memory array and populating it.
Related to https://github.com/NethermindEth/cairo-vm-go/issues/395
> Fix how lastMemIndex is calculated in DecodeMemory

- pkg/hintrunner/zero/hintcode.go
- pkg/hintrunner/zero/zerohint.go
- pkg/hintrunner/zero/zerohint_ec.go
- pkg/hintrunner/zero/zerohint_ec_test.go
- pkg/hintrunner/zero/zerohint_utils.go
Resolves #386 
@cicr99  as we discussed, i made a refactoring of `FastEcAddAssignNewY` and created a helper function `ComputeYCoordinate` so that both `EcDoubleAssignNewYV1` and `FastEcAddAssignNewY` use the same method.
> feat: `EcDoubleAssignNewYV1` hint

- README.md
- go.mod
- go.sum
- integration_tests/.env
- integration_tests/cairozero_test.go
Resolves #201 
First checking if the environment variable `INTEGRATION_TESTS_FILTERS` is set in the console.
And if not, then load it from the .env file.
> feat: Run separate cairo integration test files as a separate Go test

- pkg/hintrunner/zero/zerohint_usort_test.go
- pkg/hintrunner/zero/zerohint_utils_test.go
> refactor: Remove duplicate of `varValueEquals`

- pkg/hintrunner/hinter/operand.go
- pkg/hintrunner/zero/zerohint_ec.go
- pkg/hintrunner/zero/zerohint_signature.go
- pkg/hintrunner/zero/zerohint_utils_test.go
- pkg/vm/memory/memory_value.go
- Moves the `GetConsecutiveValues` functionality from hinter package to memory package.
- Makes necessary changes to files that invoked `GetConsecutiveValues` to match new function location.
- Resolves #384
> refactor: move GetConsecutiveValues functionality to memory package

- pkg/hintrunner/zero/hintcode.go
- pkg/hintrunner/zero/zerohint.go
- pkg/hintrunner/zero/zerohint_dictionaries.go
- pkg/hintrunner/zero/zerohint_dictionaries_test.go
Resolves #301 
This PR implements`SquashDictInnerUsedAccessesAssert` hint, which checks that `n_used_accesses` Cairo local variable is equal to the number of used accesses for a key during dict squashing.
> feat: `SquashDictInnerUsedAccessesAssert` hint

- pkg/hintrunner/zero/hintcode.go
- pkg/hintrunner/zero/zerohint.go
- pkg/hintrunner/zero/zerohint_dictionaries.go
- pkg/hintrunner/zero/zerohint_dictionaries_test.go
Resolves #297 
This PR implements `SquashDictInnerSkipLoop` hint, very similar to `SquashDictInnerContinueLoop` hint.
we don't manipulate `LoopTemps` struct here but will instead set `should_skip_loop` Cairo local variable to 0 or 1, depending on whether `current_access_indices` array still contains elements or not. 
Note i didnt respect the logic location of this hint in dict hint files, to avoid confllicts with `SquashDictInnerContinueLoop` current PR
> feat: `SquashDictInnerSkipLoop` hint

- pkg/hintrunner/zero/zerohint_ec.go
There was missing description for `ReduceV1` hint that was just merged, this PR addresses this
> Add description for `ReduceV1` hint

- pkg/hintrunner/zero/zerohint_others.go
- pkg/hintrunner/zero/zerohint_others_test.go
> Rectify wrongly implemented `MemcpyEnterScope` hint

- pkg/hintrunner/zero/hintcode.go
While starting doing integration tests for `uint256` hints (even though the integration tests wont pass because of #422 ), i noticed a few hints had formatting issue, resulting in unrecognized hints. This PR addresses this
> Update Hintcode file for `uint256` hints

- README.md
- pkg/hintrunner/hinter/operand.go
- pkg/hintrunner/zero/zerohint_dictionaries.go
- pkg/hintrunner/zero/zerohint_uint256.go
- pkg/vm/memory/memory.go
- Move WriteUint256ToAddress from hinter package to memory package
-  Move WriteToNthStructField from hinter package to memory package
- IMPORTANT NOTE:  I know that i dont have to move WriteToNthStructField but if i want to migrate the WriteUint256ToAddress  i have to move WriteToNthStructField too, because inside in the WriteUint256ToAddress i have to call WriteToNthStructField ).
- Fix the calls in the source code  for the two functions (WriteUint256ToAddress, WriteToNthStructField )
Project build sucess:
Test run sucess:
> Move WriteUint256ToAddress and WriteToNthStructField to memory package

- pkg/hintrunner/zero/hintcode.go
- pkg/hintrunner/zero/zerohint.go
- pkg/hintrunner/zero/zerohint_keccak.go
- pkg/hintrunner/zero/zerohint_keccak_test.go
> Implemented `SplitOutputMidLowHigh`

- integration_tests/cairozero_test.go
- pkg/vm/builtins/layouts.go
This PR implements the `recursive_large_output` layout, which contains : 
- output
- pedersen with 128 ratio
- rangecheck default (ie 8 ratio)
- bitwise with 8 ratio
- poseidon with 8 ratio
> feat: implement `recursive_large_output` layout

- integration_tests/cairozero_test.go
- pkg/vm/builtins/layouts.go
This PR implements the `starknet` layout, which is identical to starknet_with_keccak except there is no keccak builtin in it
Note that i used the suffix `starknet_without_keccak` , otherwise `strings.Contains()` would induce a conflict with `starknet_with_keccak` if we call it only `starknet`
> feat: implement `starknet` layout

- .github/workflows/integration-test.yml
- pkg/hintrunner/core/cairo_hintparser.go
- pkg/hintrunner/core/hint.go
- pkg/hintrunner/core/hint_test.go
- pkg/hintrunner/zero/hintcode.go
- pkg/hintrunner/zero/zerohint.go
- pkg/hintrunner/zero/zerohint_others.go
- pkg/parsers/starknet/hint.go
- pkg/vm/builtins/modulo.go
- pkg/vm/builtins/modulo_test.go
Fixes: #667 
Fixes: #637 
Fixes: #36
> Implemented EvalCircuit, Fixed bugs and wrote tests for Modbuiltin

- pkg/runner/air_input.go
- pkg/runner/runner.go
- pkg/vm/vm.go
1. Set a limit on the max number of steps
2. Moved relocatedTrace out of RelocateTrace to facilitate escape analysis
3. Removed Overhead of runtime.NewObject RelocateMemory
> VM optimizations

- pkg/vm/vm.go
When debugging (with go-delve) some optimizations are skipped which mean this function exceeds the maximum Go stack frame. When this happens, Go usually splits the function but since there was an explicit "nosplit" the code is unable to compile and makes impossible to debug any functionality that uses `RunInstruction`.
> fix(vm): remove go:nosplit from RunInstruction func

- pkg/hintrunner/zero/zerohint_ec.go
- pkg/hintrunner/zero/zerohint_keccak.go
- pkg/utils/math.go
- pkg/vm/memory/memory.go
- pkg/vm/vm.go
Use the built-in max/min from the standard library in Go 1.21 to simplify the code.  https://pkg.go.dev/builtin@go1.21.0#max
> refactor: use the built-in max/min to simplify the code
