NethermindEth/cairo-vm-go

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
> Adds a CONTRIBUTING.md and CODE_OF_CONDUCT.md

- pkg/vm/vm_test.go
Added two unit tests with negative offsets. One using AP & one using FP
> Test: Add extra tests for getCellDst using negative offsets

- pkg/vm/memory/memory_test.go
Read, write and peek tests for cell, segment and memory. Fixes #20
> Test: Add tests for read/write/peek operation on Cell, Segment and Memory

- cmd/cli/main.go
- integration_tests/cairozero_test.go
- pkg/runners/zero/zero.go
- pkg/runners/zero/zero_test.go
- pkg/vm/instruction.go
- pkg/vm/instruction_test.go
- pkg/vm/vm.go
1. Limits program execution optionally
2. Quality improvements on error texts
> Feat: Add step limit to the program execution

- pkg/hintrunner/hint.go
- pkg/hintrunner/hint_test.go
- pkg/hintrunner/hintrunner_test.go
- pkg/hintrunner/operand.go
- pkg/hintrunner/operand_test.go
- pkg/hintrunner/testutils.go
- pkg/runners/zero/zero.go
- pkg/vm/vm.go
- pkg/vm/vm_test.go
will make builtin initialization much easier
> make VM take a memory and initial context

- pkg/vm/vm.go
- pkg/vm/vm_test.go
this came up while testing RangeCheck
> Infer Op1 when Dst is known and ResLogic is Op1

- pkg/vm/vm.go
- pkg/vm/vm_test.go
Minor change on the AddImm case - Refactor AP Update Logic to Handle Negative Values and add tests
Adds tests for with positive, negative res cases
> Refactor AP Update Logic to Handle Negative Values and add tests

- pkg/hintrunner/hint.go
- pkg/hintrunner/hint_test.go
implements TestLessThanEqual.
makes cases for running the tests.
> Hint: Apply TestLessThanEqual corresponding to Fix Issue #102

- pkg/hintrunner/hint_bechmark_test.go
Add benchmarks to hints. Resolves #137
> Benchmarks for hints

- integration_tests/cairo_files/hintrefs.cairo
> intergration_tests: add multiplication test

- pkg/hintrunner/hinter/operand.go
- pkg/hintrunner/hinter/operand_test.go
- pkg/hintrunner/zero/hintparser.go
- pkg/hintrunner/zero/hintparser_test.go
Fix #206 
The handling of addresses for Uint256 elements will be solved as part of #187
> Get address for ResOperands

- pkg/hintrunner/core/hint.go
- pkg/hintrunner/hinter/utils.go
- pkg/hintrunner/zero/zerohint.go
- pkg/hintrunner/zero/zerohint_math.go
> replace resolveFieldElement with hinter.ResolveAsFelt

- pkg/hintrunner/zero/hintcode.go
- pkg/hintrunner/zero/zerohint.go
- pkg/hintrunner/zero/zerohint_math.go
- pkg/hintrunner/zero/zerohint_math_test.go
- pkg/hintrunner/zero/zerohint_test.go
- pkg/hintrunner/zero/zerohint_utils_test.go
Also implement memory address values as operanders in tests.
> pkg/hintrunner/zero: implement more math assert hints

- pkg/hintrunner/zero/hintcode.go
- pkg/hintrunner/zero/zerohint.go
- pkg/hintrunner/zero/zerohint_uint256.go
- pkg/hintrunner/zero/zerohint_uint256_test.go
> Implement split64 hint

- pkg/vm/memory/memory_value.go
- pkg/vm/memory/memory_value_test.go
- pkg/vm/vm_test.go
> pkg/vm/memory: fix sub operation result type for addr-addr

- pkg/vm/memory/memory_value.go
> vm/memory: use a enum-style type tag for MemoryValue

- pkg/hintrunner/core/hint.go
- pkg/hintrunner/core/hint_benchmark_test.go
- pkg/hintrunner/core/hint_test.go
- pkg/hintrunner/hinter/dict.go
- pkg/hintrunner/hinter/hinter.go
- pkg/hintrunner/hinter/scope.go
- pkg/hintrunner/hinter/scope_test.go
- pkg/hintrunner/hintrunner.go
- pkg/hintrunner/zero/README.md
- pkg/hintrunner/zero/hintcode.go
- pkg/hintrunner/zero/zerohint.go
- pkg/hintrunner/zero/zerohint_math.go
- pkg/hintrunner/zero/zerohint_memcpy.go
- pkg/hintrunner/zero/zerohint_test.go
Fixes #245 
Fixes #248 
Fixes #249
> Execution Scopes

- pkg/hintrunner/zero/hintcode.go
- pkg/hintrunner/zero/zerohint.go
- pkg/hintrunner/zero/zerohint_keccak.go
- pkg/hintrunner/zero/zerohint_keccak_test.go
- pkg/hintrunner/zero/zerohint_utils_test.go
> Implement KeccakWriteArgs hint

- pkg/hintrunner/zero/hintcode.go
- pkg/hintrunner/zero/zerohint.go
- pkg/hintrunner/zero/zerohint_dictionaries.go
- pkg/hintrunner/zero/zerohint_dictionaries_test.go
resolves #302 
Added Squash Dict Inner Assert Len Keys
> SquashDictInnerAssertLenKeys

- pkg/hintrunner/zero/zerohint_test.go
- pkg/hintrunner/zero/zerohint_usort_test.go
Modified the code so when the context is created, the Scope Manager is also initialised. This will solve #345
> [feat] added a default scope manager

- pkg/hintrunner/zero/hintcode.go
- pkg/hintrunner/zero/zerohint.go
- pkg/hintrunner/zero/zerohint_usort.go
- pkg/hintrunner/zero/zerohint_usort_test.go
- pkg/utils/arrays.go
Resolves https://github.com/NethermindEth/cairo-vm-go/issues/235
> Implement UsortVerifyMultiplicityBody hint

- pkg/hintrunner/zero/zerohint_dictionaries_test.go
- pkg/hintrunner/zero/zerohint_signature.go
- pkg/hintrunner/zero/zerohint_signature_test.go
@cicr99  @rodrigo-pino  the PR is ready for review, except one detail:
- for `GetPointFromX` , i dont understand what `v` operander exactly is, could you help with that?
> [feat]: Annotate signature hints + few improvements

- pkg/hintrunner/zero/zerohint.go
- pkg/hintrunner/zero/zerohint_math.go
- pkg/hintrunner/zero/zerohint_math_test.go
@cicr99  @rodrigo-pino  this PR annotates all the Math hints
> [feat]: Annotate math hints 

- pkg/hintrunner/zero/hintcode.go
- pkg/hintrunner/zero/zerohint.go
- pkg/hintrunner/zero/zerohint_dictionaries.go
- pkg/hintrunner/zero/zerohint_dictionaries_test.go
- pkg/hintrunner/zero/zerohint_utils_test.go
Resolves #303 
if we want tests to be really good, and check the value in the scope of the array of field elements `keys` after popping, i guess we should add a Case in `varValueInScopeEquals` for arrays of felts.
> feat: SquashDictInnerNextKey hint

- pkg/hintrunner/zero/hintcode.go
- pkg/hintrunner/zero/zerohint.go
- pkg/hintrunner/zero/zerohint_others.go
- pkg/hintrunner/zero/zerohint_others_test.go
> Implement MemsetContinueLoop

- pkg/hintrunner/zero/hintcode.go
- pkg/hintrunner/zero/zerohint.go
- pkg/hintrunner/zero/zerohint_others.go
- pkg/hintrunner/zero/zerohint_others_test.go
- pkg/hintrunner/zero/zerohint_utils_test.go
> Implement MemsetEnterScope

- pkg/hintrunner/zero/zerohint_others.go
- pkg/hintrunner/zero/zerohint_others_test.go
> Fixed implementation of MemcpyContinueCopying

- pkg/hintrunner/zero/hintcode.go
- pkg/hintrunner/zero/zerohint.go
- pkg/hintrunner/zero/zerohint_math.go
- pkg/hintrunner/zero/zerohint_math_test.go
> Implemented Signed Pow Hint

- pkg/hintrunner/zero/hintcode.go
- pkg/hintrunner/zero/zerohint.go
- pkg/hintrunner/zero/zerohint_uint256.go
- pkg/hintrunner/zero/zerohint_uint256_test.go
> Removed Uint256AddLow hint

- integration_tests/cairozero_test.go
> Nit : Clean Integration test 

- pkg/hintrunner/core/hint.go
> fix: set right flag value in ShouldSkipSquashLoop hint

- pkg/hintrunner/core/hint.go
- pkg/hintrunner/core/hint_test.go
- pkg/parsers/starknet/hint.go
- pkg/vm/memory/memory_value.go
> Implemented `TestLessThanOrEqualAddress`

- pkg/hintrunner/core/cairo_hintparser.go
- pkg/hintrunner/core/hint.go
- pkg/hintrunner/hinter/operand.go
- pkg/hintrunner/hinter/utils.go
- pkg/hintrunner/zero/README.md
- pkg/hintrunner/zero/hint_reference_resolver.go
- pkg/hintrunner/zero/hintparser.go
- pkg/hintrunner/zero/hintparser_test.go
- pkg/hintrunner/zero/zerohint.go
- pkg/hintrunner/zero/zerohint_blake.go
- pkg/hintrunner/zero/zerohint_dictionaries.go
- pkg/hintrunner/zero/zerohint_ec.go
- pkg/hintrunner/zero/zerohint_keccak.go
- pkg/hintrunner/zero/zerohint_math.go
- pkg/hintrunner/zero/zerohint_others.go
- pkg/hintrunner/zero/zerohint_sha256.go
- pkg/hintrunner/zero/zerohint_signature.go
- pkg/hintrunner/zero/zerohint_test.go
- pkg/hintrunner/zero/zerohint_uint256.go
- pkg/hintrunner/zero/zerohint_uint512.go
- pkg/hintrunner/zero/zerohint_usort.go
- pkg/hintrunner/zero/zerohint_utils.go
- pkg/hintrunner/zero/zerohint_utils_test.go
> Implement Reference type

- integration_tests/cairozero_test.go
- pkg/vm/builtins/layouts.go
This PR implements `dex` layout, which is very similar to the small layout , only changes the `RcUnits` value for the layout, ie, 4 vs 16
> feat: implement `dex` layout

- integration_tests/cairozero_test.go
- pkg/runner/runner_test.go
- pkg/vm/builtins/layouts.go
> Implemented `all_cairo` layout and add tests for `RangeCheck96`

- pkg/hintrunner/zero/zerohint_math_test.go
- pkg/hintrunner/zero/zerohint_signature_test.go
- pkg/hintrunner/zero/zerohint_test.go
- pkg/hintrunner/zero/zerohint_utils_test.go
- pkg/parsers/starknet/starknet.go
- pkg/parsers/starknet/starknet_test.go
- pkg/parsers/zero/zero.go
- pkg/parsers/zero/zero_test.go
- pkg/runner/air_input.go
- pkg/runner/program.go
- pkg/runner/runner.go
- pkg/runner/runner_test.go
- pkg/vm/builtins/bitwise.go
- pkg/vm/builtins/builtin_runner.go
- pkg/vm/builtins/ecdsa.go
- pkg/vm/builtins/ecop.go
- pkg/vm/builtins/keccak.go
- pkg/vm/builtins/layouts.go
- pkg/vm/builtins/names.go
- pkg/vm/builtins/pedersen.go
- pkg/vm/builtins/range_check.go
- pkg/vm/builtins/segment_arena.go
- Closes #660 
- Use name variables
- Add missing names
- Group constants(suggested improvement)
> Feat built in name literals

- CONTRIBUTING.md
- Makefile
- docs/docs/intro.md
- docs/docs/vm-fundamentals/hints.md
- integration_tests/cairo1_test.go
- pkg/vm/builtins/ecop.go
- pkg/vm/vm.go
> chore: fix some typos
